var team_to_subreddit = {
	// nfl 0-31
	'Arizona Cardinals' : 'AZCardinals',
	'Atlanta Falcons' : 'falcons',
	'Baltimore Ravens' : 'ravens',
	'Buffalo Bills' : 'buffalobills',
	'Carolina Panthers' : 'panthers',
	'Chicago Bears' : 'CHIBears',
	'Cincinnati Bengals' : 'bengals',
	'Cleveland Browns' : 'browns',
	'Dallas Cowboys' : 'cowboys',
	'Denver Broncos' : 'DenverBroncos',
	'Detroit Lions' : 'detroitlions',
	'Green Bay Packers' : 'GreenBayPackers',
	'Houston Texans' : 'Texans',
	'Indianapolis Colts' : 'colts',
	'Jacksonville Jaguars' : 'Jaguars',
	'Kansas City Chiefs' : 'KansasCityChiefs',
	'Los Angeles Chargers' : 'Chargers',
	'Los Angeles Rams' : 'LosAngelesRams',
	'Miami Dolphins' : 'miamidolphins',
	'Minnesota Vikings' : 'minnesotavikings',
	'New England Patriots' : 'Patriots',
	'New Orleans Saints' : 'Saints',
	'New York Giants' : 'NYGiants',
	'New York Jets' : 'nyjets',
	'Oakland Raiders' : 'oaklandraiders',
	'Philadelphia Eagles' : 'eagles',
	'Pittsburgh Steelers' : 'steelers',
	'San Francisco 49ers' : '49ers',
	'Seattle Seahawks' : 'Seahawks',
	'Tampa Bay Buccaneers' : 'buccaneers',
	'Tennessee Titans' : 'Tennesseetitans',
	'Washington Redskins' : 'Redskins',
	// nba 32-61
	'Atlanta Hawks' : 'AtlantaHawks',
	'Boston Celtics' : 'bostonceltics',
	'Brooklyn Nets' : 'GoNets',
	'Charlotte Hornets' : 'CharlotteHornets',
	'Chicago Bulls' : 'chicagobulls',
	'Cleveland Cavaliers' : 'clevelandcavs',
	'Dallas Mavericks' : 'Mavericks',
	'Denver Nuggets' : 'denvernuggets',
	'Detroit Pistons' : 'DetroitPistons',
	'Golden State Warriors' : 'warriors',
	'Houston Rockets' : 'rockets',
	'Indiana Pacers' : 'pacers',
	'Los Angeles Clippers' : 'LAClippers',
	'Los Angeles Lakers' : 'lakers',
	'Memphis Grizzlies' : 'memphisgrizzlies',
	'Miami Heat' : 'heat',
	'Milwaukee Bucks' : 'MkeBucks',
	'Minnesota Timberwolves' : 'timberwolves',
	'New Orleans Pelicans' : 'NOLAPelicans',
	'New York Knicks' : 'NYKnicks',
	'Oklahoma City Thunder' : 'Thunder',
	'Orlando Magic' : 'orlandomagic',
	'Philadelphia 76ers' : 'sixers',
	'Phoenix Suns' : 'suns',
	'Porland Trail Blazers' : 'ripcity',
	'Sacramento Kings' : 'kings',
	'San Antonio Spurs' : 'NBASpurs',
	'Toronto Raptors' : 'torontoraptors',
	'Utah Jazz' : 'UtahJazz',
	'Washington Wizards' : 'washingtonwizards'
}

// Detailed date for each nfl team
var nfl_team_data =  {
	'Arizona Cardinals' : {
		'location': 'Arizona',
		'name': 'Cardinals',
		'subreddit': 'AZCardinals',
		'prefix': 'Official Game Thread',
		'abbreviations': false,
		'locations': true,
		'themself': true,
		'abbreviation': 'AZ',
		'flair': null,
		'color1': '#97233F',
		'color2': '#FFB612',
	},
	'Atlanta Falcons' : {
		'location': 'Atlanta',
		'name': 'Falcons',
		'subreddit': 'falcons',
		'prefix': 'Game Thread',
		'abbreviations': false,
		'locations': true,
		'themself': true,
		'abbreviation': 'ATL',
		'flair': 'Game Day',
		'color1': '#A71930',
		'color2': '#000000',
	},
	'Baltimore Ravens' : {
		'location': 'Baltimore',
		'name': 'Ravens',
		'subreddit': 'ravens',
		'prefix': 'Game Thread',
		'abbreviations': false,
		'locations': true,
		'themself': true,
		'abbreviation': 'BAL',
		'flair': null,
		'color1': '#241773',
		'color2': '#9E7C0C',		
	},
	'Buffalo Bills' : {
		'location': 'Buffalo',
		'name': 'Bills',
		'subreddit': 'buffalobills',
		'prefix': 'Game Thread',
		'abbreviations': true,
		'locations': false,
		'themself': true,
		'abbreviation': 'BUF',
		'flair': '',
		'color1': '#00338D',
		'color2': '#C60C30',
	},
	'Carolina Panthers' : {
		'location': 'Carolina',
		'name': 'Panthers',
		'subreddit': 'panthers',
		'prefix': 'Game Thread',
		'abbreviations': false,
		'locations': true,
		'themself': true,
		'abbreviation': 'CAR',
		'flair': null,
		'color1': '#0085CA',
		'color2': '#BFC0BF',
	},
	'Chicago Bears' : {
		'location': 'Chicago',
		'name': 'Bears',
		'subreddit': 'CHIBears',
		'prefix': 'Gamethread',
		'abbreviations': false,
		'locations': false,
		'themself': true,
		'abbreviation': 'CHI',
		'flair': 'Game Thread',
		'color1': '#F26522',
		'color2': '#00143F',
	},
	'Cincinnati Bengals' : {
		'location': 'Cincinnati',
		'name': 'Bengals',
		'subreddit': 'bengals',
		'prefix': 'Game Thread',
		'abbreviations': false,
		'locations': true,
		'themself': true,
		'abbreviation': 'CIN',
		'flair': null,
		'color1': '#FB4F14',
		'color2': '#000000',
	},
	'Cleveland Browns' : {
		'location': 'Cleveland',
		'name': 'Browns',
		'subreddit': 'browns',
		'prefix': 'GAME THREAD',
		'abbreviations': false,
		'locations': false,
		'themself': true,
		'abbreviation': 'CLE',
		'flair': null,
		'color1': '#FB4F14',
		'color2': '#22150C',
	},
	'Dallas Cowboys' : {
		'location': 'Dallas',
		'name': 'Cowboys',
		'subreddit': 'cowboys',
		'prefix': '',
		'abbreviations': false,
		'locations': true,
		'themself': false,
		'abbreviation': 'DAL',
		'flair': 'Game Thread',
		'color1': '#0C264C',
		'color2': '#B0B7BC',
	},
	'Denver Broncos' : {
		'location': 'Denver',
		'name': 'Broncos',
		'subreddit': 'DenverBroncos',
		'prefix': 'Game Thread',
		'abbreviations': false,
		'locations': true,
		'themself': true,
		'abbreviation': 'DEN',
		'flair': 'Game Thread',
		'color1': '#002244',
		'color2': '#FB4F14',
	},
	'Detroit Lions' : {
		'location': 'Detroit',
		'name': 'Lions',
		'subreddit': 'detroitlions',
		'prefix': 'Official Game Thread',
		'abbreviations': false,
		'locations': true,
		'themself': true,
		'abbreviation': 'DET',
		'flair': null,
		'color1': '#046EB4',
		'color2': '#B0B7BC',
	},
	'Green Bay Packers' : {
		'location': 'Green Bay',
		'name': 'Packers',
		'subreddit': 'GreenBayPackers',
		'prefix': 'Game Thread',
		'abbreviations': false,
		'locations': true,
		'themself': true,
		'abbreviation': 'GB',
		'flair': null,
		'color1': '#24423C',
		'color2': '#FCBE14',
	},
	'Houston Texans' : {
		'location': 'Houston',
		'name': 'Texans',
		'subreddit': 'Texans',
		'prefix': 'Game Thread',
		'abbreviations': false,
		'locations': true,
		'themself': true,
		'abbreviation': 'HOU',
		'flair': null,
		'color1': '#00143F',
		'color2': '#C9243F',
	},
	'Indianapolis Colts' : {
		'location': 'Indianapolis',
		'name': 'Colts',
		'subreddit': 'colts',
		'prefix': 'Game Thread',
		'abbreviations': false,
		'locations': true,
		'themself': true,
		'abbreviation': 'IND',
		'flair': null,
		'color1': '#003D79',
		'color2': '#FFFFFF',
	},
	'Jacksonville Jaguars' : {
		'location': 'Jacksonville',
		'name': 'Jaguars',
		'subreddit': 'Jaguars',
		'prefix': 'Game Thread',
		'abbreviations': false,
		'locations': false,
		'themself': true,
		'abbreviation': 'JAX',
		'flair': null,
		'color1': '#D8A328',
		'color2': '#136677',
	},
	'Kansas City Chiefs' : {
		'location': 'Kansas City',
		'name': 'Chiefs',
		'subreddit': 'KansasCityChiefs',
		'prefix': 'Game Thread',
		'abbreviations': false,
		'locations': true,
		'themself': true,
		'abbreviation': 'KC',
		'flair': '',
		'color1': '#CA2430',
		'color2': '#FFB612',
	},
	'Los Angeles Chargers' : {
		'location': 'Los Angeles',
		'name': 'Chargers',
		'subreddit': 'Chargers',
		'prefix': 'Game Thread',
		'abbreviations': false,
		'locations': true,
		'themself': true,
		'abbreviation': 'LAC',
		'flair': null,
		'color1': '#2072BA',
		'color2': '#FDB515',
	},
	'Los Angeles Rams' : {
		'location': 'Los Angeles',
		'name': 'Rams',
		'subreddit': 'LosAngelesRams',
		'prefix': 'Game Thread',
		'abbreviations': false,
		'locations': true,
		'themself': true,
		'abbreviation': 'LAR',
		'flair': null,
		'color1': '#002244',
		'color2': '#B3995D',
	},
	'Miami Dolphins' : {
		'location': 'Miami',
		'name': 'Dolphins',
		'subreddit': 'miamidolphina',
		'prefix': 'Game Thread',
		'abbreviations': false,
		'locations': true,
		'themself': true,
		'abbreviation': 'MIA',
		'flair': null,
		'color1': '#0091A0',
		'color2': '#FF8500',
	},
	'Minnesota Vikings' : {
		'location': 'Minnesota',
		'name': 'Vikings',
		'subreddit': 'minnesotavikings',
		'prefix': 'Week',
		'abbreviations': false,
		'locations': false,
		'themself': true,
		'abbreviation': 'MIN',
		'flair': null,
		'color1': '#4F2E84',
		'color2': '#FEC62F',
	},
	'New England Patriots' : {
		'location': 'New England',
		'name': 'Patriots',
		'subreddit': 'Patriots',
		'prefix': 'Official Game Day Thread',
		'abbreviations': false,
		'locations': true,
		'themself': true,
		'abbreviation': 'NE',
		'flair': null,
		'color1': '#002244',
		'color2': '#C60C30',
	},
	'New Orleans Saints' : {
		'location': 'New Orleans',
		'name': 'Saints',
		'subreddit': 'Saints',
		'prefix': 'Game Thread',
		'abbreviations': false,
		'locations': true,
		'themself': true,
		'abbreviation': 'NO',
		'flair': null,
		'color1': '#A08A58',
		'color2': '#000000',
	},
	'New York Giants' : {
		'location': 'New York',
		'name': 'Giants',
		'subreddit': 'NYGiants',
		'prefix': 'GDT',
		'abbreviations': false,
		'locations': true,
		'themself': true,
		'abbreviation': 'NYG',
		'flair': null,
		'color1': '#0B2265',
		'color2': '#A71930',
	},
	'New York Jets' : {
		'location': 'New York',
		'name': 'Jets',
		'subreddit': 'nyjets',
		'prefix': 'Game Thread',
		'abbreviations': false,
		'locations': true,
		'themself': true,
		'abbreviation': 'NYJ',
		'flair': null,
		'color1': '#203731',
		'color2': '#FFFFFF',
	},
	'Oakland Raiders' : {
		'location': 'Oakland',
		'name': 'Raiders',
		'subreddit': 'oaklandraiders',
		'prefix': 'Game Thread',
		'abbreviations': false,
		'locations': true,
		'themself': true,
		'abbreviation': 'OAK',
		'flair': null,
		'color1': '#C4C9CC',
		'color2': '#000000',
	},
	'Philadelphia Eagles' : {
		'location': 'Philadelphia',
		'name': 'Eagles',
		'subreddit': 'eagles',
		'prefix': 'Game Thread',
		'abbreviations': false,
		'locations': true,
		'themself': true,
		'abbreviation': 'PHI',
		'flair': 'Game Thread',
		'color1': '#004C54',
		'color2': '#A5ACAF',
	},
	'Pittsburgh Steelers' : {
		'location': 'Pittsburgh',
		'name': 'Steelers',
		'subreddit': 'steelers',
		'prefix': 'Game Thread',
		'abbreviations': false,
		'locations': true,
		'themself': true,
		'abbreviation': 'PIT',
		'flair': null,
		'color1': '#FFC20E',
		'color2': '#000000',
	},
	'San Francisco 49ers' : {
		'location': 'San Francisco',
		'name': '49ers',
		'subreddit': '49ers',
		'prefix': 'Game Thread',
		'abbreviations': false,
		'locations': true,
		'themself': true,
		'abbreviation': 'SF',
		'flair': null,
		'color1': '#C9243F',
		'color2': '#C8AA76',
	},
	'Seattle Seahawks' : {
		'location': 'Seattle',
		'name': 'Seahawks',
		'subreddit': 'Seahawks',
		'prefix': 'Game Thread',
		'abbreviations': false,
		'locations': true,
		'themself': true,
		'abbreviation': 'SEA',
		'flair': null,
		'color1': '#002A5C',
		'color2': '#7AC142',
	},
	'Tampa Bay Buccaneers' : {
		'location': 'Tampa Bay',
		'name': 'Buccaneers',
		'subreddit': 'buccaneers',
		'prefix': 'Game Thread',
		'abbreviations': false,
		'locations': true,
		'themself': true,
		'abbreviation': 'TB',
		'flair': null,
		'color1': '#D40909',
		'color2': '#B0B9BF',
	},
	'Tennessee Titans' : {
		'location': 'Tennessee',
		'name': 'Titans',
		'subreddit': 'TennesseeTitans',
		'prefix': 'Game Thread',
		'abbreviations': false,
		'locations': true,
		'themself': true,
		'abbreviation': 'TEN',
		'flair': null,
		'color1': '#4095D1',
		'color2': '#00295B',
	},
	'Washington Redskins' : {
		'location': 'Washington',
		'name': 'Redskins',
		'subreddit': 'Redskins',
		'prefix': 'Game Thread',
		'abbreviations': false,
		'locations': true,
		'themself': true,
		'abbreviation': 'WAS',
		'flair': 'Game-Thread',
		'color1': '#773141',
		'color2': '#FFB612',
	},
}